### ISSUE TITLE
grey screen on the user interface 

### ISSUE THREAD

**Issue by 0x000FF4** [surge-synthesizer/surge#1149]
**Describe the bug**
I am using qtractor 0.9.9 and qt 5.9.5 and ubuntu 18.04.
When I try to open the *edit* menu for the user interface of qtractor I get only a grey screen.

**Please let us know your surge version**
The last one for ubuntu

**To Reproduce**
install qtractor on ubuntu 18.04 , import the vts dir, add some midi tracks, go to the mixer, add to given track the plugin, try to edit , voala .

**Expected behavior**
to see the user interface 

**Screenshots**
![Screenshot from 2019-09-10 23-11-44](https://user-images.githubusercontent.com/3662977/64646791-6b8dae00-d420-11e9-8b09-1dcea65924a7.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04 

**Additional context**
is there a better audio studio that I can use?

**Comment by baconpaul** [comment]
Which flavor of the plugin are you using? We've had pretty bad luck with qtractor.  (also tagging @tank-trax who knows the state of play best)

If you try the LV2 from the nightly you may have more luck?

**Comment by 0x000FF4** [comment]
this one https://github.com/surge-synthesizer/releases/releases/download/1.6.1.1/Surge-linux-x64-1.6.1.1.deb  . I you have bad luck with qtractor which studio I should use (pls no ardour beacuse I have bad luck with it :) )?

**Comment by baconpaul** [comment]
The nightly is probably a better bet.

I don't really use linux. But I test the plugin in Carla, Reaper and Bitwig and it works.

**Comment by 0x000FF4** [comment]
Nah the nightly build fails 
I have  libfreetype6-dev installed 
![Screenshot from 2019-09-10 23-32-55](https://user-images.githubusercontent.com/3662977/64648318-56664e80-d423-11e9-8f0e-0ca6f7ba0d33.png)

**Comment by jpcima** [comment]
I confirm VST2 as having problems in Qtractor. For me it's a crash.
However, LV2 is working just fine.

I'll give it a try to debug this one.

**Comment by baconpaul** [comment]
Debug the vst2? Yeah sure if you can! We all sort of banged our head off of it and figured it was some hideous version difference.

As to your build failure there - lots of things kissing from PKG_CONFIG. The azure-pipelines.yml shows you the packages you need to install to build on ubuntu 16

**Comment by baconpaul** [comment]
Linking to #545

**Comment by jpcima** [comment]
Found, it's because effGetProgramName overflows the host-side buffer.
It's size 24 at the qtractor host, surge is copying 63.
It remains to check which one is right on this matter.. when increasing the buffers, then it loads.

**Comment by 0x000FF4** [comment]
okay now I am on this 
x11platform.cpp
x11timer.cpp
x11utils.cpp
Creating target/lv2/Release/Surge.lv2
Linking surge-lv2
Running postbuild commands
python scripts/linux/generate-lv2-ttl.py target/lv2/Release/Surge.lv2/Surge.so
Traceback (most recent call last):
  File "scripts/linux/generate-lv2-ttl.py", line 18, in <module>
    dll = ctypes.cdll.LoadLibrary(dll_path)
  File "/home/x000ff4/anaconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/x000ff4/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
surge-lv2.make:177: recipe for target 'target/lv2/Release/Surge.lv2/Surge.so' failed
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
Makefile:37: recipe for target 'surge-lv2' failed
make: *** [surge-lv2] Error 2

** Build of lv2 failed**
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
make: *** [surge-lv2] Error 2

** Exiting failed lv2 build**
Complete information is in build_logs/build_lv2.log

**Comment by baconpaul** [comment]
Whoa great stuff @jpcima!

**Comment by jpcima** [comment]
@0x000FF4 it's strange this error about the cairo_xcb symbol, I will try replicating this Ubuntu build.

**Comment by 0x000FF4** [comment]
@jpcima don't waste your time I have cleaned the build and rebuild it successfully

**Comment by baconpaul** [comment]
I’m not an expert but
Cairo can compile without xcb support
Earlier in this thread you had errors consistent with Cairo and no xcb
Is it possible your Cairo shared library is built with the wrong dependencies somehow?

**Comment by tank-trax** [comment]
up to date Surge VST2 has been problematic in Qtractor causing immediate crashes when loaded but the LV2 plays very nice

**Comment by tank-trax** [comment]
@0x000FF4 

**Additional context**
is there a better audio studio that I can use?

Tracktion 7 is now free. It supports VST2 and LADSPA plugins. All you need to do is create an account at https://www.tracktion.com to get it.

**Comment by baconpaul** [comment]
@tank-trax I think with the fix I swept for @jpcima last night the surge VST2 will work in tractor also.

**Comment by tank-trax** [comment]
nice and yes. I can confirm that the VST2 now loads in qtractor without crashing.
