### ISSUE TITLE
Copying Surge to folder crashes KDE Plasma

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1288]
after copying Surge.so to a separate folder -> ~/.vst/Surge
KDE plasma crashed

not sure if it is related to Surge or not
thoughts?

here's the backtrace
```
Application: Plasma (plasmashell), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f22980b0f00 (LWP 10784))]

Thread 7 (Thread 0x7f21f8d90700 (LWP 10792)):
#0  0x00007f229f9171c9 in g_mutex_lock () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f229f8d1404 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f229f8d1994 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f229f8d1b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f22a3e3c1eb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f22a3de5d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f22a3c14093 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f22a6ec7406 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#8  0x00007f22a3c18d48 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 6 (Thread 0x7f227f1f1700 (LWP 10791)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x7f22a8a3b018) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7f22a8a3afc8, cond=0x7f22a8a3aff0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7f22a8a3aff0, mutex=0x7f22a8a3afc8) at pthread_cond_wait.c:655
#3  0x00007f22a89432c4 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#4  0x00007f22a8943309 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#5  0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7f228d17a700 (LWP 10790)):
#0  0x00007f22a3715b20 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f229f8d19f6 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f229f8d1b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f22a3e3c1eb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f22a3de5d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f22a3c14093 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f22a653d6a5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#7  0x00007f22a3c18d48 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7f228e7c3700 (LWP 10789)):
#0  0x00007f229f8ce9a7 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f229f8d1334 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f229f8d1994 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f229f8d1b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f22a3e3c1eb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f22a3de5d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f22a3c14093 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f22a653d6a5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#8  0x00007f22a3c18d48 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#10 0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7f228ffff700 (LWP 10788)):
#0  0x00007f22a3711794 in read () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f229f915e20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f229f8d14be in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f229f8d1994 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f229f8d1b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f22a3e3c1eb in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f22a3de5d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f22a3c14093 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f22a458a6e5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#9  0x00007f22a3c18d48 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#11 0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f2295f7c700 (LWP 10786)):
#0  0x00007f22a3715b69 in poll () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f22a7898150 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f22a7899ee9 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f2297cbdb89 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f22a3c18d48 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f22a3286fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f22a372082f in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f22980b0f00 (LWP 10784)):
[KCrash Handler]
#6  0x00007f21edb1c129 in ?? ()
#7  0x00005555ea33b8d0 in ?? ()
#8  0x00005555e4a055a0 in ?? ()
#9  0x00005555e4982590 in ?? ()
#10 0x00005555e4a055a0 in ?? ()
#11 0x00007f228c17b010 in ?? ()
#12 0x00007f228c17b370 in ?? ()
#13 0x00007f228c17b378 in ?? ()
#14 0x00007f228c17b370 in ?? ()
#15 0x00007f228c17b010 in ?? ()
#16 0x00007f22a643480b in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#17 0x00007f22a6521f37 in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#18 0x00007f22a6522441 in QQmlJavaScriptExpression::evaluate(bool*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#19 0x00007f22a6529f08 in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#20 0x00007f22a65338e5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#21 0x00007f22a64c2512 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#22 0x00007f22a64c3114 in QQmlIncubationController::incubateFor(int) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#23 0x00007f22a71bc9fc in ?? () from /usr/lib/x86_64-linux-gnu/libKF5Declarative.so.5
#24 0x00007f22a64c2f22 in QQmlEnginePrivate::incubate(QQmlIncubator&, QQmlContextData*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#25 0x00007f22a64bdf28 in QQmlComponent::create(QQmlIncubator&, QQmlContext*, QQmlContext*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#26 0x00007f22a700bf9f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#27 0x00007f22a700cba9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#28 0x00007f22a3e138b9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007f22a6584c2e in QQmlComponent::statusChanged(QQmlComponent::Status) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#30 0x00007f22a64bf870 in QQmlComponentPrivate::typeDataReady(QQmlTypeData*) () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#31 0x00007f22a64dfe61 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#32 0x00007f22a64d7789 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#33 0x00007f22a653d934 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#34 0x00007f22a653e02e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#35 0x00007f22a4759b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007f22a4761351 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007f22a3de7d30 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#38 0x00007f22a3dea4cd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#39 0x00007f22a3e3bdc3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#40 0x00007f229f8d17f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007f229f8d1a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007f229f8d1b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007f22a3e3c1cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#44 0x00007f22a3de5d1a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#45 0x00007f22a3dee46c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#46 0x00005555e312406f in ?? ()
#47 0x00007f22a364b09b in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#48 0x00005555e31243ea in _start ()
```

**Comment by baconpaul** [comment]
Woof. No clue. Could some background process have had the DLL open for drawing somehow?

**Comment by tank-trax** [comment]
it's Linux, so no DLL :-)

I think it's a KDE/Plasma thing, I reinstalled all the problematic libs which may correct it and sent a report to the developers, I was just curious if it could have been Surge related, like if you recognize those files as being part of the build

if not, that answers my question as to what it isn't and should help me isolate the actual issue should it recur

thanks for peeking
