### ISSUE TITLE
Build of lv2 failed - Debian Stretch

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#1333]
```
Creating target/lv2/Release/Surge.lv2
Linking surge-lv2
Running postbuild commands
python scripts/linux/generate-lv2-ttl.py target/lv2/Release/Surge.lv2/Surge.so
Traceback (most recent call last):
  File "scripts/linux/generate-lv2-ttl.py", line 18, in <module>
    dll = ctypes.cdll.LoadLibrary(dll_path)
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
surge-lv2.make:203: recipe for target 'target/lv2/Release/Surge.lv2/Surge.so' failed
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
Makefile:55: recipe for target 'surge-lv2' failed
make: *** [surge-lv2] Error 2

** Build of lv2 failed**
SurgeError.cpp
tinyxmlerror.cpp
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
make: *** [surge-lv2] Error 2

** Exiting failed lv2 build**
Complete information is in build_logs/build_lv2.log
```

**Comment by tank-trax** [comment]
just ran ....

`./build-linux.sh -p lv2 build`

and 

```
Building surge-lv2 with output in build_logs/build_lv2.log
==== Building surge-lv2 (release_x64) ====
Running prebuild commands
python scripts/linux/emit-vector-piggy.py .
Build of surge-lv2 succeeded
```

**Comment by tank-trax** [comment]
and also...

```
./build-linux.sh -l install
Installing presets
Installing VST2
Installing VST3
Installing LV2
Installing Headless
rsync: change_dir "/home/studio/src/Surge-all/surge//target/headless/Release" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
```

**Comment by baconpaul** [comment]
Cool. I did adjust the windows.wt thing today

**Comment by tank-trax** [comment]
It didn't build the LV2 assets though
only the Surge.so plugin, no *.ttl files were created

**Comment by baconpaul** [comment]
```
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
```

that's the problem

```
apt-get install cairo
```

maybe?

**Comment by baconpaul** [comment]
Or somehow get the cairo dll in your path consistently when the python runs.

**Comment by tank-trax** [comment]
I am pretty sure I have cairo installed. It never failed before. 

As well it's completely freezing up Qtractor. So bad that I have to literally shut down the computer. Mind you it's a new build of Qtractor so not sure where the breakdown is. It does the same thing with Beatzille and Bazille. Have to reboot. Am commenting from another computer.

**Comment by tank-trax** [comment]
it freezes at DataPath is ~/Documents/Surge

**Comment by baconpaul** [comment]
Can you show me the full output? Also are you at head? I thought I commented that print out last night.

**Comment by tank-trax** [comment]
I tried a clean git clone and same issue

```
git log
commit 0b1caaf5efdeb32cb0489489e31806bd78f10cab
```

**Comment by baconpaul** [comment]
hmm well I was able to build it on ubuntu. Wonder what the difference is! Let me tag in @jpcima and @falkTX to see if they have an idea?

**Comment by tank-trax** [comment]
it must be some local issue. I have some weirdness happen like where I had to reinstall stuff because basic commands were not working... will check later

**Comment by tank-trax** [comment]
I just installed 

```
libcairo-ocaml
libcairo-ocaml-dev
libenchant-dev
libglade2-dev
libgtkspell-dev
liblablgtk2-ocaml
liblablgtk2-ocaml-dev
liblablgtk2-ocaml-doc
```

still fails

```
x11platform.cpp
x11timer.cpp
x11utils.cpp
Creating target/lv2/Release/Surge.lv2
Linking surge-lv2
Running postbuild commands
python scripts/linux/generate-lv2-ttl.py target/lv2/Release/Surge.lv2/Surge.so
Traceback (most recent call last):
  File "scripts/linux/generate-lv2-ttl.py", line 18, in <module>
    dll = ctypes.cdll.LoadLibrary(dll_path)
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
surge-lv2.make:203: recipe for target 'target/lv2/Release/Surge.lv2/Surge.so' failed
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
Makefile:55: recipe for target 'surge-lv2' failed
make: *** [surge-lv2] Error 2

** Build of lv2 failed**
SurgeError.cpp
tinyxmlerror.cpp
OSError: target/lv2/Release/Surge.lv2/Surge.so: undefined symbol: cairo_xcb_surface_create
make[1]: *** [target/lv2/Release/Surge.lv2/Surge.so] Error 1
make: *** [surge-lv2] Error 2

** Exiting failed lv2 build**
Complete information is in build_logs/build_lv2.log
```

**Comment by tank-trax** [comment]
how can I build  previous commit?

**Comment by tank-trax** [comment]
why is it lurking in my conda folder???

```
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/home/studio/miniconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
```

**Comment by tank-trax** [comment]
I think I found it

**Comment by tank-trax** [comment]
I set up my environment to use conda activate and it was set up to be enabled at log in

ran `conda deactivate ` to exit the python shell and it built

sorry :-)

**Comment by baconpaul** [comment]
Oh yeah I should have thought of that! Your python environment needs to be able to find Cairo.
Glad you got it sorted!
