### ISSUE TITLE
Clap version failing in Bitwig on Linux

### ISSUE THREAD

**Issue by fractalf** [surge-synthesizer/surge#7022]
Clap version crashes in Bitwig, is it just me?

> Edit
> I reverted to 4.4.10 to debug and it works there
> I see there is another (old) issue talking about this: https://github.com/surge-synthesizer/surge/issues/6928
> Is this a Bitwig problem? (VST3 works fine in both versions)

Surge version: surge-xt-linux-x64-1.2.3

![image](https://github.com/surge-synthesizer/surge/assets/5707457/884b48d3-7575-4fa2-8f9f-97a98d5c438c)

```
> neofetch --off                                                                                                       
alf@studio 
---------- 
OS: EndeavourOS Linux x86_64 
Host: B650 GAMING X AX 
Kernel: 6.2.0.3.realtime1-4-rt 
Uptime: 2 hours, 21 mins 
Packages: 958 (pacman) 
Shell: zsh 5.9 
Resolution: 1920x1200, 1920x1200 
DE: Cinnamon 5.6.8 
WM: Mutter (Muffin) 
WM Theme: Arc-Dark (Adwaita) 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: terminator 
CPU: AMD Ryzen 7 7700 (16) @ 3.800GHz 
GPU: AMD ATI Radeon HD 4650 
GPU: AMD ATI 10:00.0 Raphael 
Memory: 3394MiB / 31238MiB 
```
![image](https://github.com/surge-synthesizer/surge/assets/5707457/1ba8ca55-cf04-450e-b6b2-b635de8dcad3)

Log
```
[2023-05-13 22:55:04.363 float-document-master error] Error loading file /home/alf/.clap/Surge XT.clap:
	com.bitwig.base.io.arN: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Error establishing metadata connection for command /opt/bitwig-studio/bin/BitwigPluginHost-X64-SSE41 metadata 1234 6 1
stdout:
PluginHost: Connecting to metadata service with id 6 on port 1234 using id 1


	at Zxx.bTP(SourceFile:40)
	at Zxx.kGM(SourceFile:14)
	at Vns.AOn(SourceFile:401)
	at Eka.run(SourceFile:88)
	at XDL.run(SourceFile:307)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Error establishing metadata connection for command /opt/bitwig-studio/bin/BitwigPluginHost-X64-SSE41 metadata 1234 6 1
stdout:
PluginHost: Connecting to metadata service with id 6 on port 1234 using id 1


	at com.bitwig.flt.library.metadata.reader.QDn.bTP(SourceFile:174)
	at com.bitwig.flt.library.metadata.reader.QDn.EWl(SourceFile:31)
	at com.bitwig.flt.library.metadata.reader.WST.AzK(SourceFile:14)
	at com.bitwig.flt.library.metadata.reader.YqD.bTP(SourceFile:22)
	at com.bitwig.flt.library.metadata.reader.YqD.EWl(SourceFile:10)
	at com.bitwig.flt.library.metadata.reader.xRs.EWl(SourceFile:41)
	at com.bitwig.flt.library.metadata.reader.xRs.EWl(SourceFile:41)
	at com.bitwig.flt.library.metadata.reader.bpn.bTP(SourceFile:44)
	at com.bitwig.flt.library.metadata.reader.bpn.EWl(SourceFile:20)
	at com.bitwig.flt.library.metadata.reader.Uqz.EWl(SourceFile:22)
	at Zxx.bTP(SourceFile:36)
	... 7 more
Caused by: java.io.IOException: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Error establishing metadata connection for command /opt/bitwig-studio/bin/BitwigPluginHost-X64-SSE41 metadata 1234 6 1
stdout:
PluginHost: Connecting to metadata service with id 6 on port 1234 using id 1


	at AUz.bTP(SourceFile:158)
	at AUz.kGM(SourceFile:179)
	at AUz.bTP(SourceFile:307)
	at com.bitwig.flt.library.metadata.reader.QDn.bTP(SourceFile:170)
	... 17 more
```

**Comment by fractalf** [comment]
OK, after some more fiddling around I found out that the cause of this issue is that I only installed the `.clap` file (just the plugin), and not everyhing else (typically in `/usr/share/surge-xt`).

I still find it weird that this shouldn't just work, so leaving the issue open and will leave it to the maintainer/devs to decide if this is something to look into

**Comment by baconpaul** [comment]
So I think there’s two issues here 

the port 1234 thing isn’t surge I think it is the bitwig out of process stuff. Surge makes no network connections. 

Absent any resources surge used to work windows and mac and I thought Linux, but without resources. I’m unclear - with the incomplete install did surge work for you?

**Comment by fractalf** [comment]
> Absent any resources surge used to work windows and mac and I thought Linux, but without resources. I’m unclear - with the incomplete install did surge work for you?

No, that's why I made this issue. So summarized:

When I **only** install the plugin:

* Bitwig 4.4.10 - all good
* Bitwig 5.0-b6 - clap not working, but vst3 is working

**Comment by fractalf** [comment]
I did some more debug. 

```sh
# Uninstalled surge (from the package I made from the .deb)
$ yay -R surge-xt

# Copied only the plugin file
$ cp ~/Downloads/Surge\ XT.clap ~/.clap
```

..and now suddenly it works :-/

Weird stuff, but this might be something with my local system, or event Bitwig, so I guess I'll just close this issue...
